version: 2.1

jobs:
  hola:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola
  adios:
    docker:
      - image: cimg/base:stable
    steps:
      - run : echo adios

      
workflows:
  hello:
    jobs:
      - hola
      - adios
       